name: D

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest]
        compiler: [dmd-master, ldc-master]
        exclude:
          - runs-on: macos-latest
            compiler: dmd-master
          - runs-on: ubuntu-24.04-arm
            compiler: dmd-master
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: master
      - uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ matrix.compiler }}

      - name: (Dub) Build & Run
        run: dub :cc -b release -q -- -###
      - name: (Dub) Test Run
        run: dub test -q
      - name: (Dub) Run build example
        working-directory: samples/build
        run: dub build -v -q
      - name: (Dub) Run nobuild example
        working-directory: samples/nobuild
        run: dub run -v -q
